import { createFileRoute } from "@tanstack/react-router";

const CONTACT = "nguyenthienbaoflo@gmail.com";
const UPDATED = "June 14, 2026";

export const Route = createFileRoute("/legal/disclaimer")({
  head: () => ({
    meta: [
      { title: "Disclaimer — IELTS Speaking AI" },
      { name: "description", content: "Important disclaimers about IELTS Speaking AI Trainer and AI-generated scores." },
      { property: "og:title", content: "Disclaimer — IELTS Speaking AI" },
      { property: "og:description", content: "Important disclaimers about IELTS Speaking AI Trainer and AI-generated scores." },
    ],
  }),
  component: Disclaimer,
});

function Disclaimer() {
  return (
    <article className="prose prose-neutral dark:prose-invert mx-auto max-w-3xl">
      <h1>Disclaimer</h1>
      <p className="text-sm text-muted-foreground">Last updated: {UPDATED}</p>

      <p>
        IELTS Speaking AI Trainer is an independent practice tool. It is <strong>not affiliated with, endorsed
        by, or sponsored by</strong> the British Council, IDP: IELTS Australia, or Cambridge Assessment English.
        "IELTS" is a registered trademark of its respective owners.
      </p>

      <h2>AI-Generated Content</h2>
      <p>Band scores, feedback, model answers, and vocabulary suggestions are generated by AI and may contain
        errors. They are estimates and not a guarantee of your performance on the official examination.</p>

      <h2>No Professional Advice</h2>
      <p>The Service is provided for educational purposes only and does not constitute professional advice.</p>

      <h2>External Links</h2>
      <p>We are not responsible for the content of third-party sites linked from the Service.</p>

      <h2>Contact</h2>
      <p><a href={`mailto:${CONTACT}`}>{CONTACT}</a></p>
    </article>
  );
}
