/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VocabularyRouteImport } from './routes/vocabulary'
import { Route as TipsRouteImport } from './routes/tips'
import { Route as SpeakingRouteImport } from './routes/speaking'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as FlashcardsRouteImport } from './routes/flashcards'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TopicTopicIdRouteImport } from './routes/topic.$topicId'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LegalRefundRouteImport } from './routes/legal.refund'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalDisclaimerRouteImport } from './routes/legal.disclaimer'
import { Route as LegalCookiesRouteImport } from './routes/legal.cookies'

const VocabularyRoute = VocabularyRouteImport.update({
  id: '/vocabulary',
  path: '/vocabulary',
  getParentRoute: () => rootRouteImport,
} as any)
const TipsRoute = TipsRouteImport.update({
  id: '/tips',
  path: '/tips',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeakingRoute = SpeakingRouteImport.update({
  id: '/speaking',
  path: '/speaking',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const FlashcardsRoute = FlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicTopicIdRoute = TopicTopicIdRouteImport.update({
  id: '/topic/$topicId',
  path: '/topic/$topicId',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => LegalRoute,
} as any)
const LegalRefundRoute = LegalRefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => LegalRoute,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LegalRoute,
} as any)
const LegalDisclaimerRoute = LegalDisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => LegalRoute,
} as any)
const LegalCookiesRoute = LegalCookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => LegalRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/flashcards': typeof FlashcardsRoute
  '/history': typeof HistoryRoute
  '/legal': typeof LegalRouteWithChildren
  '/settings': typeof SettingsRoute
  '/speaking': typeof SpeakingRoute
  '/tips': typeof TipsRoute
  '/vocabulary': typeof VocabularyRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/disclaimer': typeof LegalDisclaimerRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refund': typeof LegalRefundRoute
  '/legal/terms': typeof LegalTermsRoute
  '/topic/$topicId': typeof TopicTopicIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/flashcards': typeof FlashcardsRoute
  '/history': typeof HistoryRoute
  '/legal': typeof LegalRouteWithChildren
  '/settings': typeof SettingsRoute
  '/speaking': typeof SpeakingRoute
  '/tips': typeof TipsRoute
  '/vocabulary': typeof VocabularyRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/disclaimer': typeof LegalDisclaimerRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refund': typeof LegalRefundRoute
  '/legal/terms': typeof LegalTermsRoute
  '/topic/$topicId': typeof TopicTopicIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/flashcards': typeof FlashcardsRoute
  '/history': typeof HistoryRoute
  '/legal': typeof LegalRouteWithChildren
  '/settings': typeof SettingsRoute
  '/speaking': typeof SpeakingRoute
  '/tips': typeof TipsRoute
  '/vocabulary': typeof VocabularyRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/disclaimer': typeof LegalDisclaimerRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refund': typeof LegalRefundRoute
  '/legal/terms': typeof LegalTermsRoute
  '/topic/$topicId': typeof TopicTopicIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/flashcards'
    | '/history'
    | '/legal'
    | '/settings'
    | '/speaking'
    | '/tips'
    | '/vocabulary'
    | '/legal/cookies'
    | '/legal/disclaimer'
    | '/legal/privacy'
    | '/legal/refund'
    | '/legal/terms'
    | '/topic/$topicId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/flashcards'
    | '/history'
    | '/legal'
    | '/settings'
    | '/speaking'
    | '/tips'
    | '/vocabulary'
    | '/legal/cookies'
    | '/legal/disclaimer'
    | '/legal/privacy'
    | '/legal/refund'
    | '/legal/terms'
    | '/topic/$topicId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/flashcards'
    | '/history'
    | '/legal'
    | '/settings'
    | '/speaking'
    | '/tips'
    | '/vocabulary'
    | '/legal/cookies'
    | '/legal/disclaimer'
    | '/legal/privacy'
    | '/legal/refund'
    | '/legal/terms'
    | '/topic/$topicId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  FlashcardsRoute: typeof FlashcardsRoute
  HistoryRoute: typeof HistoryRoute
  LegalRoute: typeof LegalRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  SpeakingRoute: typeof SpeakingRoute
  TipsRoute: typeof TipsRoute
  VocabularyRoute: typeof VocabularyRoute
  TopicTopicIdRoute: typeof TopicTopicIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vocabulary': {
      id: '/vocabulary'
      path: '/vocabulary'
      fullPath: '/vocabulary'
      preLoaderRoute: typeof VocabularyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tips': {
      id: '/tips'
      path: '/tips'
      fullPath: '/tips'
      preLoaderRoute: typeof TipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speaking': {
      id: '/speaking'
      path: '/speaking'
      fullPath: '/speaking'
      preLoaderRoute: typeof SpeakingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flashcards': {
      id: '/flashcards'
      path: '/flashcards'
      fullPath: '/flashcards'
      preLoaderRoute: typeof FlashcardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topic/$topicId': {
      id: '/topic/$topicId'
      path: '/topic/$topicId'
      fullPath: '/topic/$topicId'
      preLoaderRoute: typeof TopicTopicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/refund': {
      id: '/legal/refund'
      path: '/refund'
      fullPath: '/legal/refund'
      preLoaderRoute: typeof LegalRefundRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/disclaimer': {
      id: '/legal/disclaimer'
      path: '/disclaimer'
      fullPath: '/legal/disclaimer'
      preLoaderRoute: typeof LegalDisclaimerRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/cookies': {
      id: '/legal/cookies'
      path: '/cookies'
      fullPath: '/legal/cookies'
      preLoaderRoute: typeof LegalCookiesRouteImport
      parentRoute: typeof LegalRoute
    }
  }
}

interface LegalRouteChildren {
  LegalCookiesRoute: typeof LegalCookiesRoute
  LegalDisclaimerRoute: typeof LegalDisclaimerRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalRefundRoute: typeof LegalRefundRoute
  LegalTermsRoute: typeof LegalTermsRoute
}

const LegalRouteChildren: LegalRouteChildren = {
  LegalCookiesRoute: LegalCookiesRoute,
  LegalDisclaimerRoute: LegalDisclaimerRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalRefundRoute: LegalRefundRoute,
  LegalTermsRoute: LegalTermsRoute,
}

const LegalRouteWithChildren = LegalRoute._addFileChildren(LegalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  FlashcardsRoute: FlashcardsRoute,
  HistoryRoute: HistoryRoute,
  LegalRoute: LegalRouteWithChildren,
  SettingsRoute: SettingsRoute,
  SpeakingRoute: SpeakingRoute,
  TipsRoute: TipsRoute,
  VocabularyRoute: VocabularyRoute,
  TopicTopicIdRoute: TopicTopicIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
